export const CONTRACT_ADDRESS = '0x6bE4fB10E4f7dDA882334aB5f0eFbFF335fCea76'

export const ABI = [
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"minimumBet",
            "type":"uint256"
         },
         {
            "internalType":"uint8",
            "name":"maxAmountOfBets",
            "type":"uint8"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "anonymous":false,
      "inputs":[
         
      ],
      "name":"DataReset",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"participant",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"uint8",
            "name":"selectedNum",
            "type":"uint8"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"betAmount",
            "type":"uint256"
         }
      ],
      "name":"NewBet",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"previousOwner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferred",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"uint8",
            "name":"winnerNumber",
            "type":"uint8"
         },
         {
            "indexed":false,
            "internalType":"address[255]",
            "name":"winners",
            "type":"address[255]"
         }
      ],
      "name":"WinnersDetermined",
      "type":"event"
   },
   {
      "inputs":[
         
      ],
      "name":"_maxAmountOfBets",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true
   },
   {
      "inputs":[
         
      ],
      "name":"_minimumBet",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true
   },
   {
      "inputs":[
         
      ],
      "name":"_numberOfBets",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"_playerInfo",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountBet",
            "type":"uint256"
         },
         {
            "internalType":"uint8",
            "name":"selectedNum",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"_players",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true
   },
   {
      "inputs":[
         
      ],
      "name":"_totalBet",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true
   },
   {
      "inputs":[
         
      ],
      "name":"owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true
   },
   {
      "inputs":[
         
      ],
      "name":"renounceOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"transferOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"kill",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint8",
            "name":"selectedNum",
            "type":"uint8"
         }
      ],
      "name":"bet",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function",
      "payable":true
   },
   {
      "inputs":[
         
      ],
      "name":"generateWinnerNumber",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"player",
            "type":"address"
         }
      ],
      "name":"checkPlayerExists",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true
   },
   {
      "inputs":[
         {
            "internalType":"uint8",
            "name":"winnerNumber",
            "type":"uint8"
         }
      ],
      "name":"distributePrizes",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"resetData",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   }
]