on:
  workflow_dispatch
  #release:
  #  types: [created]

name: Deploy to Amazon ECS

jobs:
    
  test_json:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Inject React/Dapp Config
      run: | 
        python inject-script.py
        cat ./frontend/src/js/config.js
      
        
